### ISSUE TITLE
Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by glaksmono** [poanetwork/solidity-flattener#26]
I'm getting the following:

```
module.js:557
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/glaksmono/Documents/solidity-flattener/index.js:3:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! solidity-flattener@2.0.0 start: `node index.js "../LYKECOIN/contracts/LykeCoinCrowdsale.sol"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the solidity-flattener@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/glaksmono/.npm/_logs/2018-02-19T14_01_14_587Z-debug.log
```

**Comment by vbaranov** [comment]
Did you install packages `npm i` before starting script?
What version of `node` and `npm` do you have?
Thanks in advance

**Comment by vbaranov** [comment]
@glaksmono did it work for you finally?

**Comment by vbaranov** [comment]
closed due to no response from user

**Comment by RadNi** [comment]
Hey. I get the same error. Here are the versions:
npm:
8.19.2
node:
v18.12.1
also have tried with node 17.9 but didn't work.
